### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by whoiskenjackson** [harlem-digital/meggierose#22]
Make the Memorabella logo 20% larger.

**Comment by trullest** [comment]
Code to increase the size of a logo image

<img alt="text" src="filename" width="20%" />

**Comment by trullest** [comment]
Code to increase the size of the logo

`<img alt="text" src="filename" width="20%" />`

**Comment by whoiskenjackson** [comment]
Hey @trullest , I believe that code would decrease the size by 20%. :). The logo is also a background image.

**Comment by whoiskenjackson** [comment]
Increased the logo to 295px wide.
